import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import SideBar from './_Components/SideBar';
import {SidebarProvider} from './_Components/shadCn/sidebar';
import Header from './_Components/Header';
import {Toaster} from './_Components/shadCn/sonner';
import ReactQueryProvider from './_lib/ReactQueryProvider';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen! overflow-x-hidden`}>
        <ReactQueryProvider>
          <SidebarProvider>
            <SideBar />
            <main className='w-screen px-3'>
              <Header />
              {children}
            </main>
          </SidebarProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
